# Generated by Django 5.1.4 on 2024-12-08 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='past_collaboration',
            field=models.ManyToManyField(to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='niche',
            field=models.ManyToManyField(to='accounts.niche'),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='platform',
            field=models.ManyToManyField(to='accounts.platform'),
        ),
        migrations.AddField(
            model_name='profile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='profile_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='profile_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_profile', to='accounts.profile'),
        ),
    ]
