# Generated by Django 5.1.4 on 2024-12-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandprofile',
            name='campaign_posted',
            field=models.ManyToManyField(to='campaigns.campaign'),
        ),
    ]
