# Generated by Django 5.1.4 on 2024-12-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
