# Generated by Django 5.1.4 on 2024-12-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_brandindustry_name_alter_brandtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='follower_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
