# Generated by Django 5.1.4 on 2024-12-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_brandprofile_campaign_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_brand',
            field=models.BooleanField(default=False),
        ),
    ]
