# Generated by Django 5.1.4 on 2024-12-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_creatorprofile_follower_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='follower_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
