# Generated by Django 5.1.4 on 2024-12-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_creatorprofile_follower_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFollowerCount',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.basemodel')),
                ('follower_count', models.IntegerField()),
                ('creator_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.creatorprofile')),
                ('platform_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.platform')),
            ],
            bases=('accounts.basemodel',),
        ),
    ]
