# Generated by Django 5.1.4 on 2024-12-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.basemodel')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            bases=('campaigns.basemodel',),
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.basemodel')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            bases=('campaigns.basemodel',),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/campaign_images')),
                ('budget', models.FloatField()),
                ('requirements', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('close', 'Closed')], default='Active', max_length=10)),
                ('audience_preferences', models.ManyToManyField(to='campaigns.audience')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='accounts.brandprofile')),
                ('content_types', models.ManyToManyField(to='campaigns.contenttype')),
            ],
            bases=('campaigns.basemodel',),
        ),
    ]
