# Generated by Django 5.1.4 on 2024-12-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.brandprofile'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='campaigns.basemodel')),
                ('message', models.TextField(blank=True, null=True)),
                ('is_interested', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('working', 'Working'), ('completed', 'Completed')], default='Pending', max_length=20)),
                ('submitted_report', models.FileField(blank=True, null=True, upload_to='campaign_reports')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('campaign_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='campaigns.campaign')),
                ('creator_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.creatorprofile')),
            ],
            bases=('campaigns.basemodel',),
        ),
    ]
