# Generated by Django 5.1.4 on 2024-12-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_proposal_completed_at_proposal_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
