# Generated by Django 5.1.4 on 2024-12-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_proposal_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('pending', 'Pending')], default='Active', max_length=10),
        ),
    ]
