# Generated by Django 5.1.4 on 2025-01-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_escrowtransaction_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='report_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='report_images',
            field=models.ImageField(blank=True, null=True, upload_to='report_images'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='report_pdfs'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='report_videos',
            field=models.FileField(blank=True, null=True, upload_to='report_videos'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('submitted', 'Submitted'), ('working', 'Working'), ('completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
