# Generated by Django 5.1.4 on 2025-01-06 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_proposal_report_description_proposal_report_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='report_images',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='report_pdf',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='report_videos',
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_images')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_images', to='campaigns.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ReportPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='report_pdfs')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_pdfs', to='campaigns.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ReportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='report_videos')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_videos', to='campaigns.proposal')),
            ],
        ),
    ]
