# Generated by Django 5.1.4 on 2025-01-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_remove_proposal_report_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportpdf',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='reportvideo',
            name='proposal',
        ),
        migrations.AddField(
            model_name='proposal',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='report_pdfs'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='report_video',
            field=models.FileField(blank=True, null=True, upload_to='report_videos'),
        ),
        migrations.DeleteModel(
            name='ReportImage',
        ),
        migrations.DeleteModel(
            name='ReportPDF',
        ),
        migrations.DeleteModel(
            name='ReportVideo',
        ),
    ]
